spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/test?characterEncoding=utf-8&serverTimezone=UTC
    username: root
    password: 123456
  main:
    web-application-type: NONE
propertiescontext:
  projectpath: D:/java
  codepackage: com.ppfly.knowledge
  tablename: t_user
  schema: test
  author: pipifeiya